# Generated by Django 6.1.1 on 2026-10-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimPlan',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.IntegerField()),
            ],
            options={
                'db_table': 'dim_plan',
            },
        ),
        migrations.CreateModel(
            name='DimTiempo',
            fields=[
                ('fecha_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('mes_orden', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('dia_semana_orden', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('dia_semana', models.CharField(max_length=20)),
                ('trimestre', models.CharField(max_length=2)),
                ('es_finde', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dim_tiempo',
            },
        ),
        migrations.CreateModel(
            name='EjecucionETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('archivo_excel', models.CharField(blank=True, default='', max_length=255)),
                ('archivo_csv', models.CharField(blank=True, default='', max_length=255)),
                ('filas_extraidas', models.IntegerField(default=0)),
                ('filas_duplicadas_eliminadas', models.IntegerField(default=0)),
                ('filas_cuarentena', models.IntegerField(default=0)),
                ('filas_validas', models.IntegerField(default=0)),
                ('filas_insertadas', models.IntegerField(default=0)),
                ('filas_actualizadas', models.IntegerField(default=0)),
                ('filas_sin_cambio', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('EN_CURSO', 'En curso')], default='EN_CURSO', max_length=20)),
                ('resumen_privacidad', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ejecucion_etl',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DimCuenta',
            fields=[
                ('cuenta_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nit_hash', models.CharField(max_length=64)),
                ('zona', models.CharField(blank=True, default='', max_length=100)),
                ('industria', models.CharField(blank=True, default='', max_length=100)),
                ('canal_adquisicion', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_registro_inconsistente', models.BooleanField(default=False)),
                ('plan_inicial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimplan')),
            ],
            options={
                'db_table': 'dim_cuenta',
            },
        ),
        migrations.CreateModel(
            name='BitacoraCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('dimension_calidad', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('regla_aplicada', models.TextField()),
                ('filas_afectadas', models.IntegerField(default=0)),
                ('decision', models.CharField(choices=[('Corregir', 'Corregir'), ('Eliminar', 'Eliminar'), ('Marcar', 'Marcar'), ('Cuarentena', 'Cuarentena'), ('No tocar', 'No tocar'), ('Anonimizar', 'Anonimizar')], max_length=20)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('responsable', models.CharField(blank=True, default='', max_length=50)),
                ('revisor', models.CharField(blank=True, default='', max_length=50)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='dashboard.ejecucionetl')),
            ],
            options={
                'db_table': 'bitacora_cambios',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='FactUso',
            fields=[
                ('uso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100)),
                ('duracion_min', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('duracion_min_faltante', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimcuenta')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimtiempo')),
            ],
            options={
                'db_table': 'fact_uso',
            },
        ),
        migrations.CreateModel(
            name='FactSuscripciones',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mrr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mrr_original', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usuarios_activos', models.IntegerField(blank=True, null=True)),
                ('mrr_corregido', models.BooleanField(default=False)),
                ('usuarios_activos_faltante', models.BooleanField(default=False)),
                ('excede_limite', models.BooleanField(default=False)),
                ('churn', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimcuenta')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimtiempo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.dimplan')),
            ],
            options={
                'db_table': 'fact_suscripciones',
                'constraints': [models.UniqueConstraint(fields=('cuenta', 'fecha'), name='uq_suscripcion_cuenta_fecha')],
            },
        ),
        migrations.CreateModel(
            name='StgRechazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_origen', models.CharField(max_length=50)),
                ('id_origen', models.CharField(max_length=50)),
                ('cuenta_id', models.IntegerField(blank=True, null=True)),
                ('fecha_id', models.IntegerField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(max_length=255)),
                ('fila_original', models.JSONField(blank=True, default=dict)),
                ('ejecucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ejecucionetl')),
            ],
            options={
                'db_table': 'stg_rechazos',
                'constraints': [models.UniqueConstraint(fields=('tabla_origen', 'id_origen'), name='uq_rechazo_origen')],
            },
        ),
    ]
