# Generated by Django 6.1.1 on 2026-10-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcuenta',
            name='plan_inicial',
        ),
        migrations.AddField(
            model_name='bitacoracambios',
            name='detalle_cambios',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejecucionetl',
            name='filas_por_tabla',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
