# Generated by Django 6.1.1 on 2026-10-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_dimcuenta_plan_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimcuenta',
            name='nit_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
